### ISSUE TITLE
Hi please help me...

### ISSUE THREAD

**Issue by rocks-man** [toffeenutt/drm-video-downloader#1]
Hello I have a problem running this script, please help me. I already set URI and file name but I don´t understand what the error is about.

The following is the traceback:

#####iframe.mediadelivery.net video downloader#####
https://iframe.mediadelivery.net/embed/27332/22f40a69-3da7-4047-818d-5d24936d0374
clase25-2302024
Traceback (most recent call last):
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_sync\connection_pool.py", line 167, in handle_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rock\Documents\ClasesPremium\bunny2.py", line 32, in <module>
    player = client.get(URI, headers=playerHeaders).text
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 1054, in get
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_transports\default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "C:\Users\Rock\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

**Comment by toffeenutt** [comment]
Hello.
This script only works on Ubuntu, not Windows.

**Comment by toffeenutt** [comment]
I briefly tested and analyzed this video and the download was successful.
The problem is that the response to 'playlist.drm' is slightly different than in my case.
The uri related to 'resolution' is different.

As a temporary measure, just modify line 78 as follows:
`start_idx = playlist.find('720p/video.drm')`
Then you can download the video.

This is still not tested on Windows.

**Comment by toffeenutt** [comment]
Thanks for reporting the issue!
The version that resolves this issue has been reflected in the main branch.

It has been modified to attempt to download at the highest resolution rather than searching for a specific resolution.

And as a result of testing on Windows, downloading the ts file was successful.
You can just play ts files.
Or, use ffmpeg to directly convert the ts file to an mp4 file.
